# Generated by Django 5.2.8 on 2025-12-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assigned_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
